cd version: "3"
services:
  phpdebug:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: phpdebug
    container_name: phpdebug
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
    ports:
      - "80:80"
    volumes:
      - "./src:/var/www/html"
