version: "3"
services:
  hello-world-demo:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: hello-world-demo
    container_name: hello-world-demo
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
    ports:
      - "80:80"
    volumes:
      - "./src:/var/www/html"
